exports.internalError = () => {
    return "An internal error has occurred. Please try again later."
}